### ISSUE TITLE
Package not compatible with Python 3.9

### ISSUE THREAD

**Issue by MrLixm** [beatreichenbach/qt-extensions#2]
Hello, fantastic package, mainly interested by the numpy Viewer.

I am working using poetry, build from python 3.9.

I have no issue adding `qt-extensions` to my dependencies as
```toml
"qt_extensions" = { git = "https://github.com/beatreichenbach/qt-extensions.git", tag = "v0.1.1"}
```
and install it using `poetry update`.

But once I execute my code which make use of it :
```python
  File "C:\Users\lcoll\AppData\Local\pypoetry\Cache\virtualenvs\agxc-gdcRGEVJ-py3.9\lib\site-packages\qt_extensions\icons.py", line 31, in MaterialIcon
    self, name: str, style: Style | None = None, size: int | None = None
TypeError: unsupported operand type(s) for |: 'EnumMeta' and 'NoneType
```

Of course this is a python 3.10 feature, and I'm on 3.9. But the issue is that the required version of python in `qt-extensions` is still 3.9 :

https://github.com/beatreichenbach/qt-extensions/blob/aa7d5d439d0654be0029b84e171c9a1aac0d01be/pyproject.toml#L9

If no 3.9 support is provided, it would be cool to at least specify it in the `pyproject.toml`.
Thanks !
Liam.

**Comment by beatreichenbach** [comment]
You're absolutely right!
I'll go through and see what the earliest version of Python is that I can reasonably support and do some tests on that. Thank you for reporting the issue.

**Comment by MrLixm** [comment]
Because I would really like to use your package, I did try to make it compatible with python 3.9.
A simple `from __future__ import annotations` fixed the type hints issues, though it seems you also used some other 3.10 features like `match` which are a bit longer to fix (and maybe other that I did not found yet)

I'm a bit sad to see that you targeted such a specific python version, it kind of restrict usability, even if I'm sure it was not your goal with this package.
So just to mention I would love you to open a bit more the targeted python versions.
Thanks again.
Liam.

**Comment by beatreichenbach** [comment]
Yeah, like I said, it shouldn't be an issue to make it backwards compatible. Some of the features like `match` I just wanted to try out for fun, nothing that can't be made to work with older versions. I'll take a look at everything and  keep you updated.
I was only using 3.10 as that was the minimum requirement for another package I was working with at the time and I never thought about going backwards.

**Comment by beatreichenbach** [comment]
Hi @MrLixm 
I went ahead and checked everything with Python 3.9. Hopefully I didn't miss anything (I haven't written proper tests for all modules) but let me know if you run into anything else.

Fix available in latest release: https://github.com/beatreichenbach/qt-extensions/releases/tag/v0.1.2

**Comment by MrLixm** [comment]
Fantastic ! I test again to confirm thanks.
